const stations = [
  {
    id: 1,
    call_sign: "WXYC",
    broadcast_frequency: "89.3",
    audio_url: "https://audio-mp3.ibiblio.org/wxyc.mp3",
    station_url: "https://wxyc.org/",
    college_name: "University of North Carolina at Chapel Hill",
    public_private: "public",
    city: "Chapel Hill",
    state: "NC",
    image: "https://radiostationusa.fm/assets/image/radio/180/WXYC.jpg",
    tags: ["none"],
  },
  {
    id: 2,
    call_sign: "KALX",
    broadcast_frequency: "90.7",
    audio_url: "https://stream.kalx.berkeley.edu:8443/kalx-128.mp3",
    station_url: "https://www.kalx.berkeley.edu/",
    college_name: "University of California, Berkeley",
    public_private: "public",
    city: "Berkeley",
    state: "CA",
    image: "https://radiostationusa.fm/assets/image/radio/180/KALXFM.png",
  },
  {
    id: 3,
    call_sign: "KVRX",
    broadcast_frequency: "91.7",
    audio_url: "https://www.kvrx.org/now_playing/stream",
    station_url: "https://kvrx.org/app/",
    college_name: "University of Texas at Austin",
    public_private: "public",
    city: "Austin",
    state: "TX",
    image:
      "https://pbs.twimg.com/profile_images/1021906128332980224/tgMrKr7O_400x400.jpg",
  },
  {
    id: 4,
    call_sign: "WCBN",
    broadcast_frequency: "88.3",
    audio_url: "http://floyd.wcbn.org:8000/wcbn-hd.mp3",
    station_url: "http://www.wcbn.org/",
    college_name: "University of Michigan",
    public_private: "public",
    city: "Ann Arbor",
    state: "Michigan",
    image:
      "http://www.wcbn.org/sites/default/files/wcbn%20logo%20color.jpg?1613678266",
  },
  {
    id: 5,
    call_sign: "WSUM",
    broadcast_frequency: "91.7",
    audio_url: "https://ice23.securenetsystems.net/WSUMFM",
    station_url: "https://wsum.org/",
    college_name: "University of Wisconsin—Madison",
    public_private: "public",
    city: "Madison",
    state: "Wisconsin",
    image: "https://www.radio.net/images/broadcasts/ec/fb/11375/c300.png",
  },
  {
    id: 5,
    call_sign: "KCOU",
    broadcast_frequency: "88.1",
    audio_url: "https://ssl.shoutcaststreaming.us:8088/stream",
    station_url: "https://kcou.fm/",
    college_name: "University of Missouri",
    public_private: "public",
    city: "Columbia",
    state: "Missouri",
    image:
      "https://upload.wikimedia.org/wikipedia/en/thumb/8/8f/Kcou-logo.jpg/200px-Kcou-logo.jpg",
  },
];

export default stations;
